### PR TITLE
Fix/turtle parser

### PR DESCRIPTION
**Pull request by shinobu**
adds [ --WS-- ] as case for the implicit BN function

### CODE REVIEW

**Comment by white-gecko** [comment]
please add more blank node examples to the test

**Comment by shinobu** [comment]
added new test cases, squashed and rebased the commits,
you can check it for errors

**Comment by shinobu** [comment]
are those enough examples?

**Comment by white-gecko** [comment]
- [ ] manual review commits
- [ ] check unit tests
- [ ] check integration tests mysql
- [ ] check integration tests virtuoso

**Pull request merged**
